name: CD
on:
  release:
    types: [created]

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Check to config repo
        uses: actions/checkout@v2
        with:
          repository: wirlleyd/argopoc-config
          token: ${{ secrets.ARGOPOC_CONFIG_TOKEN }}
          ref: homolog

      - name: perform merge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git status
          git pull
          git checkout main
          git merge main --allow-unrelated-histories --strategy-option theirs
          git push origin main
          git status

