name: CD
on:
  release:
    types: [created]
    
jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Check to config repo
        uses: actions/checkout@main
        with:
          repository: wirlleyd/argopoc-config
          token: ${{ secrets.ARGOPOC_CONFIG_TOKEN }}

      - name: merge homolog to main
        run : |
          git merge homolog

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
          git push origin main

