name: CD
on:
  release:
    types: [created]

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Check to config repo
        uses: actions/checkout@v2
        with:
          repository: wirlleyd/argopoc-config
          token: ${{ secrets.ARGOPOC_CONFIG_TOKEN }}
          ref: homolog

      - name: merge homolog to main
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'main'
          development_branch: 'homolog'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.ARGOPOC_CONFIG_TOKEN }}

